import { StyleSheet } from "react-native";
import { colors, spacing, typography } from "../../theme";

export const styles = StyleSheet.create({
  tabsSectionContainer: {
    gap: spacing.md,
    flex: 1,
  },
  container: {
    backgroundColor: colors.background,
    flex: 1,
  },
  content: {
    gap: spacing.md,
    overflow: "hidden",
  },
  profileHeader: {
    backgroundColor: colors.surface,
    padding: spacing.lg,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  avatarContainer: {
    alignItems: "center",
    marginBottom: spacing.md,
    position: "relative",
  },
  avatarActions: {
    position: "absolute",
    bottom: -4,
    flexDirection: "row",
  },
  avatarActionButton: {
    width: 32,
    height: 32,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  editAvatarButton: {
    backgroundColor: colors.primary,
    right: -30,
  },
  soloIcon: { right: -45 },
  deleteAvatarButton: {
    backgroundColor: colors.error,
    right: 30,
  },
  profileInfo: {
    alignItems: "center",
  },
  playerName: {
    fontSize: typography.h2,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: spacing.xs,
  },
  playerEmail: {
    fontSize: typography.body,
    color: colors.description,
    marginBottom: spacing.md,
  },
  playerStats: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.input,
    borderRadius: 8,
    padding: spacing.md,
  },
  statItem: {
    alignItems: "center",
    flex: 1,
  },
  statValue: {
    fontSize: typography.h3,
    fontWeight: "bold",
    color: colors.primary,
  },
  statLabel: {
    fontSize: typography.small,
    color: colors.description,
    marginTop: spacing.xs,
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: colors.border,
    marginHorizontal: spacing.md,
  },
  tabsContainer: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.xs,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    borderRadius: 8,
    gap: spacing.xs,
  },
  activeTab: {
    backgroundColor: colors.primary + "15",
  },
  tabText: {
    fontSize: typography.small,
    color: colors.description,
    fontWeight: "500",
  },
  activeTabText: {
    color: colors.primary,
    fontWeight: "bold",
  },
  tabContent: {
    flex: 1,
  },
  historySection: {
    paddingTop: spacing.sm,
    gap: spacing.md,
  },
  section: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: spacing.lg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: spacing.sm,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: typography.h3,
    fontWeight: "bold",
    color: colors.text,
  },
  detailsContainer: {
    gap: spacing.md,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  detailText: {
    fontSize: typography.body,
    color: colors.text,
  },
  skeletonContainer: {
    gap: spacing.md,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    height: 200,
    backgroundColor: colors.surface,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    gap: spacing.md,
  },
  emptyStateText: {
    color: colors.description,
    textAlign: "center",
  },
  emptyStateSubtext: {
    color: colors.placeholder,
  },
  configurationContainer: {
    gap: 8,
    marginTop: 16,
  },
  configButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: colors.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  configButtonLogout: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: colors.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.error + "30",
  },
  configButtonDelete: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    marginTop: spacing.xxl,
    backgroundColor: colors.error,
    borderRadius: 10,
  },
  configButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  configButtonText: {
    color: colors.text,
  },
  configButtonTextLogout: {
    color: colors.error,
  },
  configButtonTextDelete: {
    color: colors.white,
  },
});
